import { SQUARES, analyze, boardFor, classifyExpert, optimalPolicy, choosePolicyMove } from './rules.mjs';
import { drawNetwork, routeTimeline, LABEL, hitTestNetwork, activeExperts, EXPERTS } from './network.mjs';
import { createModel, trainingRounds, evaluateModel, exportModel, importModel } from './training.mjs';
import { benchmarkWebGPU } from './webgpu-benchmark.mjs';
import { createWebGPUTrainer, webGPUTrainerAvailable, WEBGPU_TRAINER_LIMITATION } from './webgpu-training.mjs';
const expertNames={win:'Win',block:'Block',fork:'Create fork',defendFork:'Prevent fork',position:'Center / corner',opening:'Opening',legality:'Legality',routing:'Combine answers'};
let history='';
const $=id=>document.getElementById(id);
function enableNetworkHover(){const canvas=$('network'),tip=$('network-tooltip');if(canvas.__hoverReady)return;canvas.__hoverReady=true;canvas.addEventListener('mousemove',event=>{const r=canvas.getBoundingClientRect(),hit=hitTestNetwork(canvas.__network,(event.clientX-r.left)*canvas.clientWidth/r.width,(event.clientY-r.top)*canvas.clientHeight/r.height);canvas.style.cursor=hit?'crosshair':'default';tip.hidden=!hit;if(hit){tip.textContent=hit.text;tip.style.left=`${Math.min(event.clientX+14,innerWidth-320)}px`;tip.style.top=`${Math.min(event.clientY+14,innerHeight-60)}px`}});canvas.addEventListener('mouseleave',()=>{tip.hidden=true;canvas.style.cursor='default'});}
function render(){
  const state=analyze(history), board=boardFor(history); $('history').value=history;
  $('board').replaceChildren(...board.map((mark,i)=>{const b=document.createElement('button');b.textContent=mark||SQUARES[i];b.className=mark?.toLowerCase()||'';b.disabled=!!mark||!state.valid;b.title=`${SQUARES[i]} · ${['top left','top middle','top right','middle left','center','middle right','bottom left','bottom middle','bottom right'][i]}`;b.onclick=()=>{history+=SQUARES[i];render()};return b}));
  const expert=classifyExpert(history), policy=optimalPolicy(history), config={mode:$('mode').value,seed:$('seed').value,temperature:Number($('temperature').value)||0},next=choosePolicyMove(history,config);
  const targets=policy.optimal.map((square,i)=>`${square}: ${(policy.probabilities[SQUARES.indexOf(square)]*100).toFixed(0)}%`).join(' · ');
  $('prediction').textContent=state.valid?`Target optimal set: ${targets}. Chosen (${config.mode}, seed ${config.seed}, T ${config.temperature}): ${next} · ${state.turn} to move · routed to ${expertNames[expert]}.`:`Invalid: ${state.reason}. Required output: ${next||'—'}.`;
  $('game-status').textContent=history?`History: ${history} · token ${history.length} of 8 input slots.`:'Click a square to start: X moves first.';
  const routed=activeExperts(history);$('experts').replaceChildren(...Object.entries(expertNames).map(([key,label])=>{const d=document.createElement('div');d.className='expert '+(routed.includes(key)?'active':'');d.innerHTML=`<b>${label}</b>${routed.includes(key)?'selected for this position':'inactive routing branch'}`;return d}));
  drawNetwork($('network'),history);enableNetworkHover();
  const timeline=routeTimeline(history);$('route-timeline').replaceChildren(...timeline.map((row,i)=>{const d=document.createElement('div');d.className='route '+(i===timeline.length-1?'active':'');d.textContent=`Round ${row.round}: ${row.expert in expertNames?expertNames[row.expert]:LABEL[row.expert]} (${row.history})`;return d}));
  $('expert-networks').replaceChildren(...EXPERTS.map(key=>{const active=routed.includes(key),d=document.createElement('section');d.className='expert-net '+(active?'active':'');d.innerHTML=`<h3>${expertNames[key]} ${active?'· routed':'· inactive'}</h3><div class="micro"><span>32 in</span><span class="nodes">${'<i></i>'.repeat(16)}</span><span class="nodes">${'<i></i>'.repeat(9)}</span></div><div class="micro"><span></span><span>16 hidden</span><span>9 logits</span></div>`;return d}));
  $('network-summary').textContent=`${timeline.length} routing decision${timeline.length===1?'':'s'} shown. Router selected ${routed.map(key=>expertNames[key]).join(' + ')}; their 32 → 16 → 9 expert panels are lime. Other expert panels are inactive. Weights are illustrative, not trained checkpoint weights.`;
}
$('apply').onclick=()=>{history=$('history').value.toLowerCase().slice(0,8);render()};
$('history').addEventListener('input',e=>{history=e.target.value.toLowerCase().slice(0,8)});
$('oracle').onclick=()=>{const state=analyze(history);if(state.valid&&history.length<8){history+=choosePolicyMove(history,{mode:$('mode').value,seed:$('seed').value,temperature:Number($('temperature').value)||0});render()}};
for(const id of ['mode','seed','temperature'])$(id).addEventListener('input',render);
$('reset').onclick=()=>{history='';render()};
let worker=null,gpuTrainer=null,evaluationWorker=null,evaluationId=0,playing=false,trainingHistories=[],trainingPolicies={},chartHistory=[],loadedModel=null,roundStarted=0,gpuRound=0,bestFrozenRound=null;
function drawChart(){const c=$('train-chart'),w=c.clientWidth||900,h=c.clientHeight||500,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.scale(d,d);x.fillStyle='#0d110e';x.fillRect(0,0,w,h);const pad=42;x.strokeStyle='#3c4a3e';for(let i=0;i<=4;i++){const y=pad+(h-pad*2)*i/4;x.beginPath();x.moveTo(pad,y);x.lineTo(w-pad,y);x.stroke();x.fillStyle='#a6afa4';x.fillText(`${100-i*25}%`,4,y+4)}const colors={draw:'#d1ef65',win:'#79cbe5',loss:'#f6a65c',invalid:'#e77878'};for(const [name,color] of Object.entries(colors)){x.strokeStyle=color;x.lineWidth=2;x.beginPath();chartHistory.forEach((row,i)=>{const px=pad+(w-pad*2)*(chartHistory.length===1?0:i/(chartHistory.length-1)),py=h-pad-(h-pad*2)*row[name]/100;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle=color;x.fillText(name,pad+Object.keys(colors).indexOf(name)*80,18)}chartHistory.forEach((row,i)=>{if(!row.best)return;const px=pad+(w-pad*2)*(chartHistory.length===1?0:i/(chartHistory.length-1));x.fillStyle='#fff';x.font='16px system-ui';x.fillText('★',px-5,h-10)})}
const trainConfig=()=>({layers:+$('train-layers').value,nodes:+$('train-nodes').value,rate:+$('train-rate').value,batch:32});
const renderIssue=(issue)=>{const item=document.createElement('article');item.className='expert';const heading=document.createElement('b');heading.textContent=`${issue.classification.toUpperCase()} · history “${issue.history||'∅'}” · chose ${issue.chosen}; oracle accepts ${issue.optimal.join(', ')}`;item.append(heading);const board=document.createElement('div');board.textContent=`Board: ${issue.board.slice(0,3).join(' ')} / ${issue.board.slice(3,6).join(' ')} / ${issue.board.slice(6).join(' ')}`;item.append(board);const confidence=document.createElement('div');confidence.textContent=`Model confidence: ${SQUARES.split('').map((square,index)=>`${square} ${issue.confidence[index].toFixed(2)}%`).join(' · ')}`;item.append(confidence);const teacher=document.createElement('div');teacher.textContent=`Oracle target: ${SQUARES.split('').map((square,index)=>`${square} ${issue.teacher[index].toFixed(2)}%`).join(' · ')}`;item.append(teacher);return item};
const updateFrozenReview=(evaluation,round)=>{const loss=evaluation.totals.loss,invalid=evaluation.totals.invalid,candidate={round,evaluation};const improved=!bestFrozenRound||loss+invalid<bestFrozenRound.evaluation.totals.loss+bestFrozenRound.evaluation.totals.invalid||(loss+invalid===bestFrozenRound.evaluation.totals.loss+bestFrozenRound.evaluation.totals.invalid&&loss<bestFrozenRound.evaluation.totals.loss);if(improved)bestFrozenRound=candidate;if(chartHistory.length)chartHistory.at(-1).best=improved;drawChart();const best=bestFrozenRound.evaluation;$('best-round').textContent=`Latest frozen round: ${round} · losses ${loss} / ${evaluation.total} (${evaluation.percent.loss.toFixed(3)}%) · invalid ${invalid} / ${evaluation.total} (${evaluation.percent.invalid.toFixed(3)}%). Best frozen round: ${bestFrozenRound.round} · losses ${best.totals.loss} / ${best.total} (${best.percent.loss.toFixed(3)}%) · invalid ${best.totals.invalid} / ${best.total} (${best.percent.invalid.toFixed(3)}%).`;const review=$('training-diagnostics');review.replaceChildren();const groups=[['loss',evaluation.mistakes.loss],['invalid',evaluation.mistakes.invalid]].filter(([,issues])=>issues.length<=4);if(!groups.length){review.textContent=`Frozen evaluator review is held until losses or invalid choices reach 4 or fewer. Current: ${loss} losses, ${invalid} invalid.`;return}const note=document.createElement('p');note.textContent='Frozen evaluator review: these are the model’s top choices versus the minimax oracle target. Multiple oracle-accepted squares are valid.';review.append(note);for(const [,issues] of groups)for(const issue of issues)review.append(renderIssue(issue))};
const requestFrozenReview=(model,round)=>{if(!evaluationWorker){evaluationWorker=new Worker('evaluation-worker.mjs',{type:'module'});evaluationWorker.onmessage=event=>{const message=event.data;if(message.type==='evaluation')updateFrozenReview(message.evaluation,message.round);if(message.type==='evaluation-error')$('training-diagnostics').textContent=`Frozen evaluator failed: ${message.message}`}}const id=++evaluationId;evaluationWorker.postMessage({type:'evaluate',id,round,model,histories:trainingHistories,policies:trainingPolicies})};
const paintTraining=(step,backend='CPU Worker (JavaScript)',benchmark='')=>{const total=step.totals?Object.values(step.totals).reduce((a,b)=>a+b,0):0;loadedModel=importModel(step.model);const elapsed=(performance.now()-roundStarted)/1000;$('train-status').textContent=`${backend} · round ${step.round+1}`;const outcome=step.totals?Object.fromEntries(['draw','win','loss','invalid'].map(name=>[name,100*(step.totals[name]||0)/total])):null;if(outcome)chartHistory.push(outcome);requestFrozenReview(step.model,step.round+1);$('train-outcome').textContent=outcome?`Round ${step.round+1} completed in ${elapsed.toFixed(3)}s: loss ${outcome.loss.toFixed(3)}% · invalid ${outcome.invalid.toFixed(3)}% remaining${benchmark?` · ${benchmark}`:''}`:`Round ${step.round+1} GPU updates completed in ${elapsed.toFixed(3)}s${benchmark?` · ${benchmark}`:''}. Frozen evaluator review is running in a Worker.`;roundStarted=performance.now();drawChart()};
async function ensureTrainingData(){if(trainingHistories.length)return;const data=await fetch('data/reachable-policy.json').then(r=>r.json());trainingHistories=data.examples.map(row=>row.history);trainingPolicies=Object.fromEntries(data.examples.map(row=>[row.history,row.policy]).filter(([,policy])=>policy));}
function stopWorker(){if(worker){worker.terminate();worker=null}}
function stopGpu(){if(gpuTrainer){gpuTrainer.destroy();gpuTrainer=null}}
function startWorker(){if(worker)return;worker=new Worker('training-worker.mjs',{type:'module'});worker.onmessage=e=>{if(e.data.type==='round')paintTraining(e.data);if(e.data.type==='backend')$('train-status').textContent=e.data.backend;if(e.data.type==='paused')$('train-status').textContent+=' · paused; current weights retained'};worker.onerror=e=>{$('train-outcome').textContent=`Worker failure: ${e.message}`;playing=false}};
async function runGpuTraining(){if(!webGPUTrainerAvailable()){ $('train-status').textContent='WebGPU unavailable; falling back to CPU Worker (JavaScript).'; $('backend-choice').value='cpu'; return runCpuTraining() }stopWorker();$('train-status').textContent='WebGPU dense training · preparing GPU buffers and pipelines…';$('train-outcome').textContent='Starting palace-9 WebGPU round; progress will report every 8 of 4,519 positions.';await new Promise(resolve=>requestAnimationFrame(resolve));if(!gpuTrainer)gpuTrainer=await createWebGPUTrainer(loadedModel||createModel(trainConfig()));playing=true;roundStarted=performance.now();const result=await gpuTrainer.trainRound(trainingHistories,trainConfig().rate,async progress=>{if(progress.index===1||progress.index%8===0||progress.index===progress.total){const elapsed=(performance.now()-roundStarted)/1000;const rate=progress.index/Math.max(elapsed,.001);$('train-status').textContent=`WebGPU dense training · position ${progress.index.toLocaleString()} / ${progress.total.toLocaleString()} · ${rate.toFixed(1)} positions/s`;await new Promise(resolve=>requestAnimationFrame(resolve))}},()=>playing);const gpuMs=performance.now()-roundStarted;if(!playing)return;loadedModel=result.model;gpuRound++;paintTraining({model:exportModel(loadedModel),round:gpuRound-1,totals:null},'WebGPU dense training',`WebGPU training round: ${gpuMs.toFixed(1)}ms. CPU comparison is recorded only from a separate CPU run.`)}
async function runCpuTraining(){stopGpu();await ensureTrainingData();startWorker();playing=true;roundStarted=performance.now();worker.postMessage({type:'start',histories:trainingHistories,config:trainConfig(),model:loadedModel?exportModel(loadedModel):null})}
async function runTraining(){await ensureTrainingData();try{if($('backend-choice').value==='webgpu')await runGpuTraining();else await runCpuTraining()}catch(error){stopGpu();$('backend-choice').value='cpu';$('train-status').textContent=`WebGPU failed (${error.message}); CPU Worker fallback selected.`;await runCpuTraining()}}
$('train-start').onclick=runTraining;
$('train-validate').onclick=async()=>{await ensureTrainingData();if(!loadedModel){$('train-outcome').textContent='No loaded/trained weights to validate.';return}const r=evaluateModel(loadedModel,trainingHistories);$('train-outcome').textContent=`Frozen validation: loss ${r.percent.loss.toFixed(3)}% · invalid ${r.percent.invalid.toFixed(3)}% · invalid-context correction ${r.percent.correction.toFixed(3)}% · incorrect ${r.percent.incorrect.toFixed(3)}%. This is independent of the in-training chart.`};
$('webgpu-benchmark').onclick=async()=>{const r=await benchmarkWebGPU();$('train-outcome').textContent=r.available?`WebGPU compute probe: ${r.operations.toLocaleString()} float operations in ${r.ms.toFixed(3)}ms. Select WebGPU and run training for a real CPU-vs-WebGPU round measurement.`:`WebGPU unavailable: ${r.reason}. CPU Worker remains active.`};
$('backend-choice').onchange=()=>{$('train-status').textContent=$('backend-choice').value==='webgpu'?(webGPUTrainerAvailable()?`WebGPU selected. ${WEBGPU_TRAINER_LIMITATION}`:'WebGPU unavailable; Start will fall back to CPU Worker (JavaScript).'):'CPU Worker (JavaScript) selected.'};
$('train-download').onclick=()=>{if(!loadedModel){$('train-outcome').textContent='No loaded/trained weights to download.';return}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(exportModel(loadedModel))],{type:'application/json'}));a.download='palace-9-model.json';a.click();URL.revokeObjectURL(a.href)};
$('train-load').onchange=async e=>{try{loadedModel=importModel(JSON.parse(await e.target.files[0].text()));stopWorker();stopGpu();playing=false;chartHistory=[];drawChart();$('train-status').textContent=`Loaded ${loadedModel.widths.join(' → ')} weights.`;$('train-outcome').textContent='Loaded model. Use Validate loaded weights for frozen metrics.'}catch(error){$('train-outcome').textContent=`Model load failed: ${error.message}`}e.target.value=''};
$('train-pause').onclick=()=>{playing=false;if(worker)worker.postMessage({type:'pause'});if(gpuTrainer)$('train-status').textContent+=' · pause takes effect after this GPU round; current GPU buffers retained'};
$('train-reset').onclick=()=>{playing=false;stopWorker();stopGpu();loadedModel=null;gpuRound=0;bestFrozenRound=null;chartHistory=[];$('train-status').textContent='Weights reset. Change layers/nodes, choose backend, then Start.';$('train-outcome').textContent='No completed rounds yet.';$('best-round').textContent='Best frozen round: none yet.';$('training-diagnostics').textContent='Detailed evaluator review appears when a frozen round has 4 or fewer losses and/or 4 or fewer invalid choices.';drawChart()};
drawChart();
render();
