import { boardFor, classifyExpert } from './rules.mjs';
export const EXPERTS=['win','block','fork','defendFork','position','opening','legality','routing'];
export const LABEL={win:'Win',block:'Block',fork:'Create fork',defendFork:'Prevent fork',position:'Center / corner',opening:'Opening',legality:'Legality',routing:'Combine answers'};
export const selectedExpert=history=>classifyExpert(history);
const companion={win:'position',block:'defendFork',fork:'position',defendFork:'block',position:'opening',opening:'position',legality:'routing',routing:'legality'};
export function activeExperts(history=''){const primary=selectedExpert(history),secondary=companion[primary]||'routing';return primary===secondary?[primary]:[primary,secondary]}
export function routeTimeline(history=''){const rows=[{round:0,history:'∅',expert:selectedExpert('')}];for(let i=1;i<=history.length;i++)rows.push({round:i,history:history.slice(0,i),expert:selectedExpert(history.slice(0,i))});return rows}
const noise=(a,b,c=0)=>Math.sin((a+1)*12.9898+(b+1)*78.233+(c+1)*37.719)*.5+.5;
const signed=(a,b,c=0)=>noise(a,b,c)*2-1;
const plus=n=>`${n>=0?'+':''}${n.toFixed(4)}`;
export const signedWeightColor=(value,alpha=1)=>value>0?`rgba(246,166,92,${alpha})`:value<0?`rgba(121,203,229,${alpha})`:`rgba(166,175,164,${alpha})`;
export function strongestRoutes(edges,contextLength,expertIndexes,limit=3){const finalStage=Math.max(...edges.map(edge=>edge.stage)),routes=[];const walk=(stage,fromIndex,chain)=>{const candidates=edges.filter(edge=>edge.stage===stage&&edge.fromIndex===fromIndex&&(stage!==finalStage||expertIndexes.includes(edge.toIndex)));for(const edge of candidates){const next=[...chain,edge];if(stage===finalStage)routes.push({edges:next,score:next.reduce((score,item)=>score*Math.abs(item.weight),1)});else walk(stage+1,edge.toIndex,next)}};for(let input=0;input<contextLength;input++)walk(0,input,[]);return routes.sort((a,b)=>b.score-a.score).slice(0,limit).map(route=>route.edges)};
const pointDistance=(x,y,x1,y1,x2,y2)=>{const dx=x2-x1,dy=y2-y1,t=Math.max(0,Math.min(1,((x-x1)*dx+(y-y1)*dy)/(dx*dx+dy*dy)));return Math.hypot(x-(x1+t*dx),y-(y1+t*dy))};
export function hitTestNetwork(graph,x,y){
 let node;for(const item of graph.nodes){const d=Math.hypot(x-item.x,y-item.y);if(d<=(node?.d??Infinity)&&d<=10)node={...item,d}}if(node)return {kind:'node',text:`${node.layer} · unit ${node.index+1} · illustrative bias ${plus(node.bias)}`};
 let edge;for(const item of graph.edges){const d=pointDistance(x,y,item.x1,item.y1,item.x2,item.y2);if(d<=(edge?.d??Infinity)&&d<=7)edge={...item,d}}if(edge)return {kind:'edge',text:`${edge.from} → ${edge.to} · illustrative weight ${plus(edge.weight).replace('-', '−')}`};return null;
}
export function drawNetwork(canvas,history=''){
 const dpr=devicePixelRatio||1,w=canvas.clientWidth||960,h=canvas.clientHeight||500;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const active=activeExperts(history),expertIndexes=active.map(key=>EXPERTS.indexOf(key));
 const cols=[{name:'8 context slots',n:8,x:58},{name:'board-state encoder · 9',n:9,x:w*.22},{name:'layer 1 · 32',n:32,x:w*.42},{name:'layer 2 · 32',n:32,x:w*.62},{name:'8 experts',n:8,x:w*.80},{name:'9 outputs',n:9,x:w-48}];const pos=(column,i)=>column.name.startsWith('board-state')?{x:column.x+(i%3-1)*15,y:56+(Math.floor(i/3)+1)*(h-112)/4}:{x:column.x,y:56+(i+1)*(h-112)/(column.n+1)};
 const board=boardFor(history),graph={nodes:[],edges:[]};for(let ci=0;ci<cols.length;ci++){for(let i=0;i<cols[ci].n;i++){const p=pos(cols[ci],i);graph.nodes.push({layer:cols[ci].name,index:i,x:p.x,y:p.y,bias:signed(i,ci,7),state:ci===1?(board[i]||'·'):null})}}for(let ci=0;ci<cols.length-1;ci++){const a=cols[ci],b=cols[ci+1];for(let i=0;i<a.n;i++)for(let j=0;j<b.n;j++){const p=pos(a,i),q=pos(b,j),weight=signed(i,j,ci),chosen=(ci===3&&expertIndexes.includes(j))||(ci===4&&expertIndexes.includes(i));graph.edges.push({stage:ci,fromIndex:i,toIndex:j,from:ci===0?`context ${i+1}`:`${a.name} unit ${i+1}`,to:ci===4?`${LABEL[EXPERTS[j]]} expert`:`${b.name} unit ${j+1}`,x1:p.x,y1:p.y,x2:q.x,y2:q.y,weight,chosen})}}
 const routeEdges=graph.edges.filter(edge=>edge.stage<4),routes=strongestRoutes(routeEdges,history.length,expertIndexes),strongest=new Set(routes.flat());graph.strongestRoutes=routes;for(const edge of graph.edges){ctx.strokeStyle=edge.chosen?'rgba(209,239,101,.22)':'rgba(166,175,164,.075)';ctx.lineWidth=edge.chosen?1:.42;ctx.beginPath();ctx.moveTo(edge.x1,edge.y1);ctx.lineTo(edge.x2,edge.y2);ctx.stroke()}for(const edge of strongest){const magnitude=Math.abs(edge.weight);ctx.strokeStyle=signedWeightColor(edge.weight,.3+magnitude*.55);ctx.lineWidth=1.2+magnitude*1.3;ctx.beginPath();ctx.moveTo(edge.x1,edge.y1);ctx.lineTo(edge.x2,edge.y2);ctx.stroke()}
 ctx.font='12px ui-monospace,monospace';ctx.textAlign='center';ctx.fillStyle='#a6afa4';for(const col of cols)ctx.fillText(col.name,col.x,22);for(let ci=0;ci<cols.length;ci++){const col=cols[ci];for(let i=0;i<col.n;i++){const p=pos(col,i),node=graph.nodes.find(item=>item.layer===col.name&&item.index===i),selected=ci===4&&expertIndexes.includes(i);ctx.fillStyle=selected?'#d1ef65':ci===1?(node.state==='X'?'#f6a65c':node.state==='O'?'#79cbe5':'#3c4a3e'):signedWeightColor(node.bias,.3+Math.abs(node.bias)*.7);if(ci===1)ctx.fillRect(p.x-6,p.y-6,12,12);else{ctx.beginPath();ctx.arc(p.x,p.y,selected?7:ci===0?5:3,0,Math.PI*2);ctx.fill()}if(ci===0){ctx.fillStyle='#f2f4ea';ctx.textAlign='right';ctx.fillText(String.fromCharCode(97+i),p.x-10,p.y+4)}if(ci===1){ctx.fillStyle=node.state==='·'?'#a6afa4':'#111512';ctx.textAlign='center';ctx.fillText(node.state,p.x,p.y+4)}if(ci===4){ctx.fillStyle=selected?'#d1ef65':'#a6afa4';ctx.textAlign='left';ctx.fillText(LABEL[EXPERTS[i]],p.x+10,p.y+4)}}}
 canvas.__network=graph;return graph;
}
