export const SQUARES = 'abcdefghi';
export const INVALID_TOKEN = '!';
// Each permutation maps a source square index to its transformed destination.
export const D4_PERMUTATIONS = [[0,1,2,3,4,5,6,7,8],[2,1,0,5,4,3,8,7,6],[8,7,6,5,4,3,2,1,0],[6,7,8,3,4,5,0,1,2],[0,3,6,1,4,7,2,5,8],[6,3,0,7,4,1,8,5,2],[8,5,2,7,4,1,6,3,0],[2,5,8,1,4,7,0,3,6]];
export function transformSquares(values,permutation){const output=Array(values.length).fill(0);for(let source=0;source<9;source++)output[permutation[source]]=values[source];return output;}
export function inversePermuteSquares(values,permutation){const output=[...values];for(let source=0;source<9;source++)output[source]=values[permutation[source]];return output;}
export function transformFeatures(features,permutation){const board=Array(27).fill(0);for(let source=0;source<9;source++)board.splice(permutation[source]*3,3,...features.slice(source*3,source*3+3));return [...board,...features.slice(27)];}
export function canonicalizeFeatures(features){const candidates=D4_PERMUTATIONS.map((permutation,transformIndex)=>({features:transformFeatures(features,permutation),permutation,transformIndex}));candidates.sort((a,b)=>a.features.join(',').localeCompare(b.features.join(','))||a.transformIndex-b.transformIndex);return candidates[0];}
const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
const MOVE_ORDER = [4,0,2,6,8,1,3,5,7];
export function encodeHistory(history='') { return [...history].map(token => SQUARES.indexOf(token)); }
export function boardFor(history='') { const board=Array(9).fill(null);for(let i=0;i<history.length;i++)board[SQUARES.indexOf(history[i])]=i%2?'O':'X';return board; }
export function winningLines(board){return LINES.filter(line=>board[line[0]]&&line.every(index=>board[index]===board[line[0]]));}
export function winner(board) { return winningLines(board)[0] ? board[winningLines(board)[0][0]] : null; }
export function gameResult(history='',finalMove=''){
  const complete=finalMove&&SQUARES.includes(finalMove)?history+finalMove:history,board=boardFor(complete),lines=winningLines(board),line=lines[0]||null;
  if(line)return {winner:board[line[0]],line,lines,draw:false,terminal:true};
  return {winner:null,line:null,lines:[],draw:complete.length===9&&board.every(Boolean),terminal:complete.length===9&&board.every(Boolean)};
}
export function analyze(history='') { const tokens=[...history];let valid=tokens.length<=8,reason='';if(!tokens.every(t=>SQUARES.includes(t))){valid=false;reason='non-square token'}if(new Set(tokens).size!==tokens.length){valid=false;reason='repeated square'}const board=valid?boardFor(history):Array(9).fill(null),won=valid&&winner(board);if(won){valid=false;reason=`${won} already won`}return {valid,reason,board,turn:tokens.length%2?'O':'X',last:tokens.at(-1)||''}; }
function immediate(board,mark) {for(let i=0;i<9;i++)if(!board[i]){board[i]=mark;const ok=winner(board)===mark;board[i]=null;if(ok)return i}return -1}
function score(board,turn,root) {const won=winner(board);if(won)return won===root?10:-10;const open=board.map((v,i)=>v?null:i).filter(i=>i!==null);if(!open.length)return 0;const next=turn==='X'?'O':'X',values=open.map(i=>{board[i]=turn;const v=score(board,next,root);board[i]=null;return v});return turn===root?Math.max(...values):Math.min(...values)}
export function optimalPolicy(history='') {const state=analyze(history);if(!state.valid)return {valid:false,optimal:[INVALID_TOKEN],probabilities:SQUARES.split('').map(()=>0),scores:Array(9).fill(null),invalidToken:INVALID_TOKEN};const scores=Array(9).fill(null),open=MOVE_ORDER.filter(i=>!state.board[i]);const winning=open.filter(i=>{state.board[i]=state.turn;const yes=winner(state.board)===state.turn;state.board[i]=null;return yes});const other=state.turn==='X'?'O':'X',blocks=open.filter(i=>{state.board[i]=other;const yes=winner(state.board)===other;state.board[i]=null;return yes});for(const i of open){state.board[i]=state.turn;scores[i]=score(state.board,other,state.turn);state.board[i]=null}const best=Math.max(...scores.filter(v=>v!==null)),optimal=(winning.length?winning:blocks.length?blocks:MOVE_ORDER.filter(i=>scores[i]===best)).map(i=>SQUARES[i]),probabilities=SQUARES.split('').map(s=>optimal.includes(s)?1/optimal.length:0);return {valid:true,optimal,probabilities,scores,best}}
const rng=seed=>{let n=(Number(seed)>>>0)||1;n=Math.imul(n^(n>>>16),0x45d9f3b);n=Math.imul(n^(n>>>16),0x45d9f3b)^(n>>>16);return()=>((n=(n*1664525+1013904223)>>>0)/4294967296)};
export function difficultySettings(level='hard'){return {easy:{mode:'experimental',temperature:12},normal:{mode:'experimental',temperature:4},hard:{mode:'varied',temperature:0},expert:{mode:'deterministic',temperature:0}}[level]||{mode:'varied',temperature:0}};
export function choosePolicyMove(history='',{mode='deterministic',seed=1983,temperature=0}={}) {const policy=optimalPolicy(history);if(!policy.valid)return policy.optimal[0];if(mode==='deterministic'||temperature<=0&&mode==='experimental')return policy.optimal[0];const legal=SQUARES.split('').filter((_,i)=>policy.scores[i]!==null),random=rng(seed);if(mode==='varied')return policy.optimal[Math.floor(random()*policy.optimal.length)];const weights=legal.map((s,i)=>Math.exp((policy.scores[SQUARES.indexOf(s)]||-10)/Math.max(.01,temperature))),total=weights.reduce((a,b)=>a+b,0);let pick=random()*total;for(let i=0;i<legal.length;i++){pick-=weights[i];if(pick<=0)return legal[i]}return legal.at(-1)}
export function oracleMove(history='') {return choosePolicyMove(history,{mode:'deterministic'})}
export function classifyExpert(history='') {const state=analyze(history);if(!state.valid)return 'legality';if(immediate([...state.board],state.turn)>=0)return 'win';const other=state.turn==='X'?'O':'X';if(immediate([...state.board],other)>=0)return 'block';if(history.length===0)return 'opening';return history.length<3?'position':'fork'}
export function featureVector(history='') {const state=analyze(history);let safe='';if(state.valid)safe=history;else for(const token of history){if(!analyze(safe+token).valid)break;safe+=token}const decoded=boardFor(safe),turn=safe.length%2?'O':'X',vector=[];for(const cell of decoded)vector.push(cell==='X'?1:0,cell==='O'?1:0,cell?0:1);vector.push(turn==='X'?1:0,turn==='O'?1:0,!state.valid?1:0,state.reason==='repeated square'?1:0);return vector}
