import assert from 'node:assert/strict';
import { analyze, encodeHistory, oracleMove, classifyExpert, optimalPolicy, choosePolicyMove, featureVector, difficultySettings, gameResult } from './rules.mjs';

assert.deepEqual(encodeHistory('aei'), [0, 4, 8]);
assert.equal(oracleMove('ab'), 'e', 'X should take the center after a,b');
assert.equal(oracleMove('aebd'), 'c', 'X should complete the top row');
assert.equal(oracleMove('abd'), 'g', 'O should block X first-column win');
assert.equal(oracleMove('aa'), '!', 'a repeated square returns the invalid sentinel');
assert.equal(oracleMove('adbec'), '!', 'a terminal history returns the invalid sentinel');
assert.equal(classifyExpert('aebd'), 'win');
assert.equal(classifyExpert('abd'), 'block');
assert.equal(analyze('aebd').valid, true);
assert.deepEqual(featureVector('aa').slice(-2),[1,1],'repeated-square input carries invalid and repeated-square flags');
assert.deepEqual(featureVector('a!').slice(-2),[1,0],'other malformed input carries invalid but not repeated-square flag');
const policy=optimalPolicy('');
assert.ok(Math.abs(policy.probabilities.reduce((a,b)=>a+b,0)-1)<1e-12);
assert.ok(policy.optimal.length>1,'opening has more than one equally optimal move');
assert.equal(choosePolicyMove('',{mode:'varied',seed:1983}),choosePolicyMove('',{mode:'varied',seed:1983}),'seeded varied play is reproducible');
assert.deepEqual(difficultySettings('easy'),{mode:'experimental',temperature:12});
assert.deepEqual(difficultySettings('normal'),{mode:'experimental',temperature:4});
assert.deepEqual(difficultySettings('hard'),{mode:'varied',temperature:0});
assert.deepEqual(difficultySettings('expert'),{mode:'deterministic',temperature:0});
assert.ok(new Set([1983,1984,1985,1986].map(seed=>choosePolicyMove('',{...difficultySettings('hard'),seed}))).size>1,'different game seeds choose among equal optimal openings');
assert.deepEqual(gameResult('aebdch'),{winner:'X',line:[0,1,2],draw:false,terminal:true});
assert.deepEqual(gameResult('abcfdgeih'),{winner:null,line:null,draw:true,terminal:true});
assert.equal(gameResult('ab').terminal,false);
console.log('tic-tac-toe rules: ok');
