import assert from 'node:assert/strict';
import fs from 'node:fs';

const page=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('./app.mjs',import.meta.url),'utf8');
assert.match(page,/id="players"/,'player-count control is present');
assert.match(page,/<option value="0">0<\/option>/,'zero-player option remains available');
assert.match(page,/<option value="1" selected>1<\/option>/,'one-player mode is the default');
assert.match(page,/<option value="2">2<\/option>/,'two-player option remains available');
assert.match(page,/id="board"/,'playable board remains');
assert.match(page,/id="history"/,'sequence inspector remains');
assert.match(page,/id="network"/,'weight inspector remains');
assert.match(page,/id="precision"/,'release artifact selector is present');
assert.match(page,/value="fp32"/);
assert.match(page,/value="f16"/);
assert.match(page,/value="q6_k"/);
assert.match(page,/value="q4_k_m"/);
assert.match(app,/loadQwenPrecision/,'changing the selector loads a packed release artifact');
assert.doesNotMatch(page,/id="oracle"/,'redundant ask-policy control is removed');
assert.match(app,/\$\('reset'\)\.disabled=mode===0/,'zero-player mode disables manual new-game control');
assert.match(app,/game=newGame\(game\).*players\(\)===0|players\(\)===0.*game=newGame\(game\)/,'zero-player mode starts a new game itself');
assert.match(app,/autoplayDelay\(autoGamesPlayed\)/,'autoplay pace is regulated by completed policy-vs-policy games');
assert.match(app,/autoGamesPlayed\+\+;game=newGame\(game\)/,'each completed self-play game advances the speed schedule');
assert.ok(page.indexOf('<h2>Play</h2>')<page.indexOf('id="board"'),'the board stays in the left play panel');
assert.ok(page.indexOf('<h2>Palace-9</h2>')<page.indexOf('id="players"'),'player selection stays in the Palace-9 panel');
assert.ok(page.indexOf('<h2>Model</h2>')<page.indexOf('id="precision"'),'precision selection has a dedicated model panel');
assert.match(page,/\.board button\.empty\{color:#485148\}/,'empty board labels stay deliberately subdued');
assert.match(app,/mark\?\.toLowerCase\(\)\|\|'empty'/,'unoccupied squares use the empty visual treatment');
assert.doesNotMatch(page,/<h2>Play<\/h2>/,'the compact board panel has no title');
assert.doesNotMatch(page,/id="game-status"/,'the compact board panel has no bottom status text');
assert.match(page,/id="draw-overlay"[^>]*hidden[^>]*>Draw</,'the board includes a hidden draw overlay');
assert.match(app,/overlay\.hidden=!terminalLabel/,'overlay visibility is driven by a terminal result');
assert.match(page,/\.draw-overlay\{[^}]*color:#e77878/,'draw overlay uses large red treatment');
assert.match(page,/grid-template-columns:minmax\(260px,340px\)/,'desktop grid keeps the play field compact');
assert.match(page,/<option value="0">0<\/option><option value="1" selected>1<\/option><option value="2">2<\/option>/,'player picker uses compact numeric options');
assert.match(page,/for="precision">Precision<\/label>/,'artifact picker is labelled Precision');
assert.match(page,/<option value="fp32" selected>FP32<\/option><option value="f16">F16<\/option><option value="q6_k">Q6_K<\/option><option value="q4_k_m">Q4_K_M<\/option>/,'precision picker uses compact release labels');
assert.match(page,/id="apply">Evaluate<\/button>/,'inspect action uses a concise label');
assert.match(page,/class="compact-controls"/,'game and artifact controls use the compact shared row');
assert.match(page,/\.compact-move\{grid-template-columns:9ch auto;width:max-content;margin-top:8px\}/,'Evaluate stays beside the eight-token history input');
assert.match(page,/\.compact-move input\{width:9ch/,'history input visibly accommodates all eight tokens');
assert.match(page,/<select id="players"[^>]*><option value="0">0<\/option><option value="1" selected>1<\/option><option value="2">2<\/option><\/select><\/div>\s*<div class="compact-controls"><button id="reset">New game<\/button>/,'New game has its own row below Players');
assert.match(page,/<button id="reset">New game<\/button><\/div>\s*<p class="palace-note"><strong>PALACE:<\/strong> Predictive Autonomous Learning And <del>Nuclear<\/del> Contingency Evaluation is a fictional training exercise for a 3×3 theater-of-war simulation, powered by deep neural networks and generative AI models\. The blips and trajectories on this screen are fantasy, not real-world data\. It is a simulation, not an operational system\.<\/p>/,'New game is followed by the PALACE fictional-simulation note with Nuclear struck through');
assert.match(page,/\.palace-note\{font:12px\/1\.45 ui-monospace,monospace;color:var\(--muted\);margin:12px 0 0\}/,'PALACE note remains compact beneath New game');
assert.doesNotMatch(page,/PALANCE/,'obsolete PALANCE wording is absent');
assert.ok(page.indexOf('id="players"')<page.indexOf('id="reset"'),'New game follows Players');
assert.ok(page.indexOf('id="apply"')<page.indexOf('id="precision"'),'Precision follows Evaluate');
assert.match(page,/\.compact-move\+\.compact-controls\{margin-top:8px\}/,'control rows are vertically separated after Evaluate');
assert.doesNotMatch(page,/shall we play a game/i,'top-page tagline is removed');
assert.doesNotMatch(page,/Play a constrained tic-tac-toe game/i,'top-page explanatory text is removed');
assert.doesNotMatch(page,/<h1>Palace-9<\/h1>/,'top-page title is removed');
assert.match(page,/<h2>Palace-9<\/h2>/,'control panel uses the correct Palace-9 title');
assert.doesNotMatch(page,/Published causal Qwen2-MoE weight inspector/,'map title is removed');
assert.doesNotMatch(page,/id="network-summary"/,'post-credit inspector text is removed');
assert.match(page,/class="map-panel"/,'map sits in a dedicated floating section');
assert.match(page,/\.map-panel\{margin-top:22px\}/,'map section has spacing without the gray panel treatment');
assert.match(page,/\.network-note\{[^}]*white-space:nowrap/,'desktop map credit remains on one line');
assert.match(page,/href="https:\/\/lewismoten\.com"/,'designer credit links to Lewis Moten’s website');
assert.match(page,/href="https:\/\/git\.lewismoten\.com\/skynet\/palace9"/,'live repository link points to the Palace-9 repository');
assert.match(page,/href="https:\/\/github\.com\/lewismoten\/palace-9"/,'planned GitHub repository link uses the confirmed palace-9 name');
assert.match(page,/\.draw-overlay\[hidden\]\{display:none\}/,'hidden outcomes cannot be overridden by overlay layout CSS');
assert.match(app,/const terminalLabel=result\.winner\?`Winner: \$\{result\.winner\}`:result\.draw\?'Draw':!state\.valid\?'Invalid':''/,'winner overlay has an explicit label');
assert.match(page,/\.x\{color:#ffbd78!important\}/,'X marker has high contrast');
assert.match(page,/\.o\{color:#93ddf5!important\}/,'O marker has high contrast');
assert.match(page,/grid-template-columns:minmax\(260px,340px\) minmax\(280px,1fr\) minmax\(220px,\.7fr\)/,'desktop layout provides a third model column');
assert.match(page,/\.model-panel \.spec\{grid-template-columns:1fr\}/,'model info cards stack within the narrow third column');
assert.match(page,/font:700 clamp\(28px,7\.5vw,48px\)/,'terminal overlay stays within the compact board');
assert.match(app,/overlay\.hidden=!terminalLabel/,'terminal overlay remains hidden until an outcome exists');
assert.doesNotMatch(page,/id="prediction"/,'policy-inspection status text is removed');
assert.doesNotMatch(page,/Two-player mode never applies the recommendation/,'two-player explanatory copy is removed');
assert.match(page,/id="parameters"/,'loaded model parameter count has an info card');
assert.match(page,/id="artifact-size"/,'selected release artifact has a file-size info card');
assert.match(app,/RELEASE_ARTIFACT_BYTES=\{fp32:2598856,f16:1304384,q6_k:1065216,q4_k_m:1065216\}/,'file-size card uses exact released-artifact byte sizes');
assert.match(app,/formatFileSize\(RELEASE_ARTIFACT_BYTES\[\$\('precision'\)\.value\]\)/,'file-size card follows the selected precision');
assert.doesNotMatch(page,/Qwen decoder layer/,'decoder-layer info card is removed');
assert.doesNotMatch(page,/routing experts/,'routing-expert info card is removed');
assert.match(page,/\.network-note a\{color:var\(--accent\)/,'map-credit links use the lime accent');
assert.doesNotMatch(page,/id="train-start"/,'obsolete browser-training controls are removed');
assert.doesNotMatch(page,/id="quantization-table"/,'obsolete quantization table is removed');
console.log('focused playable-site contract: ok');
