import assert from 'node:assert/strict';
import { contextSlotIcon, outputSlotIcon, historyFlags, encoderSlotPosition, matrixGridPosition, edgeOpacity, edgeOpacityFor, EXPERTS, activeExperts, NETWORK_ICON_SIZE } from './network.mjs';

assert.equal(NETWORK_ICON_SIZE,32,'context and output board icons are doubled to 32 pixels');
assert.deepEqual(contextSlotIcon('ai',0),{token:'a',mark:'X',cell:0});
assert.deepEqual(contextSlotIcon('ai',1),{token:'i',mark:'O',cell:8});
assert.deepEqual(contextSlotIcon('ai',2),{token:'',mark:'',cell:-1});
const chosen=outputSlotIcon('a',[.1,.2,.3,.4,0,0,0,0,0],3);
assert.equal(chosen.token,'d');
assert.equal(chosen.mark,'O');
assert.equal(chosen.confidence,40);
assert.equal(chosen.chosen,true);
assert.equal(outputSlotIcon('a',[.1,.2,.3,.4,0,0,0,0,0],9).token,'!');
assert.deepEqual(historyFlags('aa'),{invalid:true,repeatedSquare:true});
assert.deepEqual(historyFlags('a!'),{invalid:true,repeatedSquare:false});
assert.deepEqual(historyFlags('ai'),{invalid:false,repeatedSquare:false});
const top=encoderSlotPosition(0,200,500),dupe=encoderSlotPosition(9,200,500);
assert.equal(top.y,210,'transformed board is vertically centered');
assert.equal(dupe.y,280,'dupe remains adjacent to the compact board');
assert.equal(encoderSlotPosition(3,200,500).y-top.y,20,'transformed board rows use compact grid spacing');
const first=matrixGridPosition(0,36,300,500),last=matrixGridPosition(35,36,300,500);
assert.equal(first.columns,6,'36 units render as a six-by-six matrix');
assert.equal(last.row,5);assert.equal(last.column,5);
assert.equal(matrixGridPosition(15,16,300,500).columns,4,'16 units remain a four-by-four matrix');
assert.equal(edgeOpacity(0),.25);
assert.equal(edgeOpacity(.5),.625);
assert.equal(edgeOpacity(5),1);
assert.equal(edgeOpacityFor({stage:0,fromIndex:0,weight:0},null,''),.25,'empty context slot is dim');
assert.equal(edgeOpacityFor({stage:0,fromIndex:0,weight:0},null,'a'),1,'occupied context slot brightens its lines');
assert.equal(edgeOpacityFor({stage:1,fromIndex:0,weight:.8},{encoded:[0]},'a'),.25,'inactive transformed cell stays dim');
assert.ok(Math.abs(edgeOpacityFor({stage:1,fromIndex:0,weight:.8},{encoded:[1]},'a')-.85)<1e-12,'active transformed cell reflects weight');
const routerFirst=matrixGridPosition(0,9,300,500),routerLast=matrixGridPosition(8,9,300,500);
assert.equal(routerFirst.columns,3,'nine MoE experts render as a three-by-three router matrix');
assert.equal(routerLast.row,2);assert.equal(routerLast.column,2);
assert.deepEqual(EXPERTS,['expert-1','expert-2','expert-3','expert-4','expert-5','expert-6','expert-7','expert-8','expert-9']);
assert.deepEqual(activeExperts('',null),['expert-1','expert-2'],'fallback view does not claim a semantic role');
console.log('network slot icons: ok');
