import assert from 'node:assert/strict';
import { createModel, evaluateModel, exportModel, importModel, invalidCorrectionTarget } from './training.mjs';
assert.equal(invalidCorrectionTarget('aa'),'a');
assert.equal(invalidCorrectionTarget('aj'),'a');
const model=createModel({layers:2,nodes:8,experts:3,expertNodes:5});
const report=evaluateModel(model,['','a','ab']);
assert.equal(report.total,3);
assert.ok('draw' in report.percent && 'invalid' in report.percent && 'correction' in report.percent);
const exported=exportModel(model);
assert.equal(exported.format,'palace-9-moe/v1');
assert.equal(exported.architecture,'board-state-moe');
assert.equal(exported.modelName,'palace-9');
assert.equal(exported.expansion,'Predictive Adversarial Learning and Contingency Evaluator');
const restored=importModel(exported);
assert.deepEqual(restored,model);
assert.throws(()=>importModel({format:'wrong'}),/format/);
console.log('validation and MoE model exchange: ok');
