import assert from 'node:assert/strict';
import { createModel, predict, trainingRounds, exportModel, importModel } from './training.mjs';

const model=createModel({layers:2,nodes:8,experts:3,expertNodes:5});
assert.equal(model.architecture,'board-state-moe');
assert.deepEqual(model.encoder.widths,[29,9]);
assert.deepEqual(model.trunk.widths,[9,8,8]);
assert.equal(model.router.weights.length,3);
assert.equal(model.experts.length,3);
assert.deepEqual(model.experts[0].widths,[8,5,9]);
const result=predict(model,'ae');
assert.equal(result.probabilities.length,9);
assert.equal(result.board.length,9);
assert.equal(result.gates.length,3);
assert.ok(Math.abs(result.gates.reduce((sum,value)=>sum+value,0)-1)<1e-9);
assert.ok(result.gates.every(value=>value>0));
const before=JSON.stringify(model);
const original=JSON.parse(before);
const run=trainingRounds(['','a','ae'],{layers:2,nodes:8,experts:3,expertNodes:5,batch:2,rate:.01});
const step=run.next().value;
assert.equal(step.index,2);assert.equal(step.total,3);
assert.equal(step.model.architecture,'board-state-moe');
assert.notEqual(JSON.stringify(step.model),before);
assert.notDeepEqual(step.model.encoder.weights,original.encoder.weights);
assert.notDeepEqual(step.model.router.weights,original.router.weights);
assert.notDeepEqual(step.model.experts[0].weights,original.experts[0].weights);
const restored=importModel(exportModel(step.model));
assert.equal(restored.architecture,'board-state-moe');
assert.throws(()=>importModel({...exportModel(step.model),experts:[]}),/Invalid MoE model shape/);
const legacy=exportModel(step.model);
const sentinel={...legacy,format:'palace-9-moe/v3',outputTokens:[...'abcdefghi!'],invalidToken:'!',encoder:{...legacy.encoder,widths:[31,9],weights:legacy.encoder.weights.map(row=>[...row,0,0])},experts:legacy.experts.map(expert=>({...expert,widths:[expert.widths[0],expert.widths[1],10],weights:[expert.weights[0], [...expert.weights[1],Array(expert.widths[1]).fill(0)]]}))};
const sentinelRestored=importModel(sentinel);
assert.equal(sentinelRestored.experts[0].widths.at(-1),10);
console.log('board-state MoE training generator: ok');
