import { featureVector, optimalPolicy, SQUARES } from './rules.mjs';
const rand=i=>Math.sin(i*91.17)*.08;
const zeros=n=>Array(n).fill(0);const mat=(r,c,k)=>Array.from({length:r},(_,i)=>Array.from({length:c},(_,j)=>rand(k+i*c+j)));
const softmax=v=>{const m=Math.max(...v),x=v.map(n=>Math.exp(n-m)),s=x.reduce((a,b)=>a+b,0);return x.map(n=>n/s)};
const pick=result=>result.probabilities.indexOf(Math.max(...result.probabilities));
export function createModel({layers=2,nodes=32}={}){const widths=[29,...Array(Number(layers)).fill(Number(nodes)),9],weights=[];for(let i=0;i<widths.length-1;i++)weights.push(mat(widths[i+1],widths[i],i+1));return {widths,weights,steps:0}}
export function predict(model,history){let a=featureVector(history),acts=[a];for(const w of model.weights){a=w.map(row=>row.reduce((s,n,i)=>s+n*acts.at(-1)[i],0));if(acts.length<model.weights.length)a=a.map(Math.tanh);acts.push(a)}return {acts,probabilities:softmax(a)}}
export function invalidCorrectionTarget(history=''){let prefix='';for(const token of history){const next=prefix+token;if(!optimalPolicy(next).valid)break;prefix=next}return prefix.at(-1)||''}
export function trainOne(model,history,rate=.025){const policy=optimalPolicy(history);if(!policy.valid)return null;const {acts,probabilities}=predict(model,history),target=policy.probabilities;let delta=probabilities.map((p,i)=>p-target[i]);for(let l=model.weights.length-1;l>=0;l--){const prior=acts[l],w=model.weights[l];for(let r=0;r<w.length;r++)for(let c=0;c<w[r].length;c++)w[r][c]-=rate*delta[r]*prior[c];if(l){const before=acts[l],next=zeros(before.length);for(let i=0;i<before.length;i++){for(let r=0;r<w.length;r++)next[i]+=w[r][i]*delta[r];next[i]*=1-before[i]*before[i]}delta=next}}model.steps++;return {policy,probabilities}}
export function classifyOutcome(result){const index=pick(result),policy=result.policy;if(policy.probabilities[index]>0)return policy.best===10?'win':'draw';return policy.scores[index]===-10?'loss':'invalid'}
export function invalidContexts(histories){const all=new Set;for(const history of histories.filter(Boolean)){all.add(history+history.at(-1));all.add(history+'j')}return [...all]}
export function evaluateModel(model,histories){const totals={draw:0,win:0,loss:0,invalid:0,correction:0,incorrect:0};for(const history of histories){const result={...predict(model,history),policy:optimalPolicy(history)};totals[classifyOutcome(result)]++}for(const history of invalidContexts(histories)){const target=invalidCorrectionTarget(history),answer=SQUARES[pick(predict(model,history))];totals[answer===target?'correction':'incorrect']++}const total=histories.length,invalidTotal=totals.correction+totals.incorrect;return {total,invalidTotal,totals,percent:Object.fromEntries(Object.entries(totals).map(([k,v])=>[k,100*v/(k==='correction'||k==='incorrect'?invalidTotal:total)]))}}
export function exportModel(model){return {format:'noughtlear-browser-model/v1',widths:model.widths,weights:model.weights,steps:model.steps}}
export function importModel(data){if(!data||data.format!=='noughtlear-browser-model/v1')throw Error('Unsupported model format');if(!Array.isArray(data.widths)||!Array.isArray(data.weights)||data.weights.length!==data.widths.length-1)throw Error('Invalid model shape');for(let i=0;i<data.weights.length;i++)if(data.weights[i].length!==data.widths[i+1]||data.weights[i].some(row=>!Array.isArray(row)||row.length!==data.widths[i]))throw Error('Invalid model matrix');return {widths:data.widths,weights:data.weights,steps:Number(data.steps)||0}}
export function* trainingRounds(histories,config,state={model:createModel(config)}){const batch=Number(config.batch||32);while(true){const totals={draw:0,win:0,loss:0,invalid:0};for(let i=0;i<histories.length;i++){const result=trainOne(state.model,histories[i],Number(config.rate||.025));if(result)totals[classifyOutcome(result)]++;if((i+1)%batch===0||i===histories.length-1)yield {model:state.model,round:state.round||0,index:i+1,total:histories.length,totals}}state.round=(state.round||0)+1}}
